<a href="https://colab.research.google.com/github/GunelXelilli/Numpy/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4,5,6,7,8,9])
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a1[1:3]

array([2, 3])

In [4]:
a1[-2:]

array([8, 9])

In [5]:
a1.ndim #returns an integer = number of dimensions of a1

1

In [6]:
a1.shape

(9,)

In [7]:
a1.dtype

dtype('int64')

In [9]:
type(a1)

numpy.ndarray

In [10]:
a1.size

9

In [11]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a2.ndim #returns an integer = number of dimensions of a2

2

In [16]:
a2.dtype

dtype('int64')

In [13]:
a2.shape

(3, 3)

In [14]:
type(a2)

numpy.ndarray

In [15]:
a2.size

9

In [18]:
a2[1:2] #first column ,second row

array([[4, 5, 6]])

In [19]:
a2[1,:]

array([4, 5, 6])

In [20]:
a2[:,1] #firs column 0,1,2

array([2, 5, 8])

In [21]:
a2[a2>5]

array([6, 7, 8, 9])

In [22]:
a2[2]

array([7, 8, 9])

In [23]:
a2[1:3,2]

array([6, 9])

In [24]:
a2[1:,0:2]

array([[4, 5],
       [7, 8]])

In [28]:
a3 = np.array([
    [[1, 2, 3], [3, 4, 5], [6, 7, 8]],
    [[2, 4, 7], [6, 7, 8], [9, 3, 1]]
])
a3

array([[[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]],

       [[2, 4, 7],
        [6, 7, 8],
        [9, 3, 1]]])

In [29]:
a3.shape #shape(bloks,rows,columns)

(2, 3, 3)

In [30]:
a3.ndim

3

In [31]:
a3.size

18

In [32]:
type(a3)

numpy.ndarray

In [33]:
a3.dtype

dtype('int64')

In [35]:
a3[1,1:,1:]

array([[7, 8],
       [3, 1]])

In [37]:
a3[1,0:2,1:]

array([[4, 7],
       [7, 8]])

In [38]:
np.zeros((2,3)) #creating matrix with '0'

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones((3,4)) #creating matrix with '1'

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.full((3,3),7) #creating a matrix filled the number '7'

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [41]:
np.eye(3) #3x3 matrix with '0' and '1'

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.arange(0,10) # 10 is not included

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
b=np.arange(0,10,2) #arange(start,stop,step)
b

array([0, 2, 4, 6, 8])

In [46]:
b*2

array([ 0,  4,  8, 12, 16])

In [48]:
np.linspace(0,10,)  #

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [50]:
np.random.seed(3)
random_arr=np.random.randint(1,10,size=(3,3))
random_arr

array([[9, 4, 9],
       [9, 1, 6],
       [4, 6, 8]])

In [51]:
a3.T

array([[[1, 2],
        [3, 6],
        [6, 9]],

       [[2, 4],
        [4, 7],
        [7, 3]],

       [[3, 7],
        [5, 8],
        [8, 1]]])

In [52]:
a3.shape,a2.T.shape

((2, 3, 3), (3, 3))

In [53]:
np.dot(a2,a2.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [54]:
a2@a2.T

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [64]:
resultt = np.matmul(a2, a2.T)
resultt

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [65]:
np.sum(a2)

np.int64(45)

In [66]:
np.mean(a2)

np.float64(5.0)

In [67]:
a2.sum()

np.int64(45)

In [58]:
import time
start=time.time()
arr=np.random.randint(1,10,size=(1_000_0000))**2

end=time.time()

end-start

0.31415843963623047

In [61]:
import time

start=time.time()
result=[]
for i in range(10000000):
  result.append(i**2)

end=time.time()
end-start

1.5508131980895996